name: Deploy with OIDC

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy with Pulumi OIDC
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Authenticate with Pulumi
        uses: pulumi/auth-actions@v1
        with:
          organization: antonyben006
          requested-token-type: urn:pulumi:token-type:access_token:organization
      
      - name: Load ESC Environment
        uses: pulumi/esc-action@v1
        with:
          environment: antonyben006/aws-oidc-dev
          export-environment-variables: true
      
      - name: Install Dependencies
        run: npm install
      
      - name: Pulumi Up
        uses: pulumi/actions@v5
        with:
          command: up
          stack-name: antonyben006/myworkshop/dev
